import {images} from "../assets";
import { DatosExcursiones, Activity } from '../interfaces/reservadoInterface';

export const excursiones:Array<DatosExcursiones>=[
    {
        id:1,
        titulo:"Habana",        
        imagen:require("../assets/images/excursion-bici.jpg"),//images.bici,
        actividades:[
            {
            id:1,    
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
        },
        {
            id:2,
            name:"Pasear por el malecon",
            foto:require("../assets/images/buceo.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"A pie",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
        },
        {
            id:3,
            name:"Visita al museo de la revolucion",
            foto:require("../assets/images/excursion3.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
        },
        {
            id:4,
            name:"Bailar con Osmany",
            foto:require("../assets/images/giraldilla.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
        },
        {
            id:5,
            name:"Tomar ron",
            foto:require("../assets/images/estadio-latinoamericano.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
        }
    ]
        

    },
    {
        id:2,
        titulo:"Camaguey",
        imagen:require("../assets/images/buceo.jpg"),
        actividades:[
            {
                id:1,
            name:"Caminar por Camaguey",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
        },
        {
            id:2,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
            
        },
        {
            id:3,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
            
        },
        {
            id:4,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
            
        },
        {
            id:5,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
           
        }
    ]
    },
    {
        id:3,
        titulo:"Cienfuegos",
        imagen:require("../assets/images/excursion3.jpg"),
        actividades:[
            {
                id:1,
            name:"Visitar a Juana",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
            
        },
        {
            id:2,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
            
        },
        {
            id:3,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
            
        },
        {
            id:4,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
            
        },
        {
            id:5,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
           
        }
    ]
    },
   {
        id:4,
        titulo:"Santiago de Cubas",
        imagen:require("../assets/images/salsa.jpg"),
        actividades:[
            {
                id:1,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
            
        },
        {
            id:2,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
            
        },
        {
            id:3,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
            
        },
        {
            id:4,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
            
        },
        {
            id:5,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
           
        }
    ]
    },
    {
        id:5,
        titulo:"Matanzas",
        imagen:require("../assets/images/salsa.jpg"),
        actividades:[
            {
                id:1,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
            
        },
        {
            id:2,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
            
        },
        {
            id:3,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
            
        },
        {
            id:4,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
            
        },
        {
            id:5,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
           
        }
    ]
    },
    {
        id:6,
        titulo:"Pinar del Rio",
        imagen:require("../assets/images/pinar.jpg"),
        actividades:[
            {
                id:1,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
            
        },
        {
            id:2,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
            
        },
        {
            id:3,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
            
        },
        {
            id:4,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
            
        },
        {
            id:5,
            name:"Andar la Habana en bici",
            foto:require("../assets/images/excursion-bici.jpg"),
            guia:"si",
            idioma:"ingles",
            tipo_transp:"Bicicleta",
            categoria:"Experiencia",
            isBookmark:true,
            provincia:"Habana",
            desde:"2021-01-15",
            hasta:"2021-01-23",
            hora:"10:30",
            direccion:"Picota 123 entre Agel y Espada",
            descripcion:"Este tour esta ideado para visitar varios puntos de la Habana, con el objetivo de mostrar los lugares mas bellos de la Habana.",
           
        }
    ]
    },
    /* {
        id:7,
        titulo:"Senderimo",
        desde:"2021-01-15",
        hasta:"2021-01-23",
        hora:"10:30",
        imagen:images.senderismos,
        guia:"si",
        idioma:"ingles",
        tipo_transp:"Bus",
        categoria:"Tour turistico",
        isBookmark:false,
        provincia: "Pinar del Rio"
    },
    {
        id:8,
        titulo:"Explora nuestras costas",
        desde:"2021-01-15",
        hasta:"2021-01-23",
        hora:"10:30",
        imagen:images.senderismos,
        guia:"si",
        idioma:"ingles",
        tipo_transp:"Bus",
        categoria:"Tour turistico",
        isBookmark:false,
        provincia: "Camaguey"
    },
    {
        id:9,
        titulo:"Explora nuestras costas",
        desde:"2021-01-15",
        hasta:"2021-01-23",
        hora:"10:30",
        imagen:images.senderismos,
        guia:"si",
        idioma:"ingles",
        tipo_transp:"Bus",
        categoria:"Tour turistico",
        isBookmark:false,
        provincia: "Villa Clara"
    },
    {
        id:10,
        titulo:"Explora nuestras costas",
        desde:"2021-01-15",
        hasta:"2021-01-23",
        hora:"10:30",
        imagen:images.senderismos,
        guia:"si",
        idioma:"ingles",
        tipo_transp:"Bus",
        categoria:"Tour turistico",
        isBookmark:false,
        provincia: "Holguin"
    },  */
]
